# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5343dbabe87a9b6ee2fae24a542f55b78925be3eb6424da3f16b3b208e67c88029a23b0ccb483e0b83f4dcc64050574a56945108d647060d91f9e6bd8b8a1a82

test:
  secret_key_base: 12842677df2e69fbc9d65ac99fdf5b4eb7c4942d73fc9222189700f81b49a0dd1869b1d5338b31ab4b24494eadc09ea5f209ea3773b63f4ff30fee2780f2a24f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
